### ISSUE TITLE
win10_x64下闪退

### ISSUE THREAD

**Issue by lanybass** [ZSAIm/iqiyi-parser#9]
```
D:\IQIYI-parser\Win7-64-compile>main.exe
[Ctrl + C] to copy the iqiyi video url, and go back to see this console.
" https://www.iqiyi.com/v_19rqv8kir4.html?list=19rr9l4atu "
+---------------------------------------------------------------+
?拮拥睦寺眯?0190314预告 包贝尔定制浪漫之旅惨被吐槽-综艺-高清正版视频在线观看–爱奇艺Traceback (most recent call last):
  File "main.py", line 240, in <module>
  File "main.py", line 182, in main
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
[9656] Failed to execute script main
```

**Comment by ZSAIm** [comment]
可能是编码的问题，可以尝试在main.py的14行加入如下代码
```python
import sys
reload(sys)
sys.setdefaultencoding('utf-8') 

```

**Comment by ZSAIm** [comment]
如果没有python环境可以尝试如下版本
[dist.zip](https://github.com/ZSAIm/iqiyi-parser/files/2971774/dist.zip)

**Comment by lanybass** [comment]
```
D:\dist>main.exe https://www.iqiyi.com/v_19rqv8kir4.html?list=19rr9l4atu
[Ctrl + C] to copy the iqiyi video url, and go back to see this console.
" https://www.iqiyi.com/v_19rqv8kir4.html?list=19rr9l4atu "
+---------------------------------------------------------------+
?拮拥睦寺眯?0190314预告 包贝尔定制浪漫之旅惨被吐槽-综艺-高清正版视频在线观看–爱奇艺Traceback (most recent call last):
  File "main.py", line 252, in <module>
  File "main.py", line 194, in main
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
[2480] Failed to execute script main
```
用你上面的dist.zip，一样

**Comment by YFTX2015** [comment]
我的也是一样闪退，用的也是win10_64

**Comment by ZSAIm** [comment]
解析并没问题，应该就是第三方模块colorama的问题。这段时间会抽点时间写个GUI界面，放弃使用colorama。

**Comment by lanybass** [comment]
> 解析并没问题，应该就是第三方模块colorama的问题。这段时间会抽点时间写个GUI界面，放弃使用colorama。

界面倒不用，把颜色去掉也挺好

**Comment by ZSAIm** [comment]
还是做一个把，没有进度显示看起来不舒服。
做个简单的就行了，花不了多久。

**Comment by ZSAIm** [comment]
程序已上传，可以尝试下是否能使用。

**Comment by lanybass** [comment]
没毛病，老铁，可以下载了
但是
1.菜单里的exit按了没反应
2.解析后不下载按x关闭，提示：Failed to execute script main
建议记录错误日志到文件
